
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CALLIGRAPHER CHINESE_NAME DYNASTY FIND INFO STYLE WORK\nquery : find_calligrapher_detail\n      | find_work_representative\n      | find_style\n      | find_dynasty_calligraphers\n      | find_calligrapher_info\n      | find_direct\n      | find_calligrapher_style\nfind_calligrapher_detail : FIND CALLIGRAPHER CHINESE_NAMEfind_work_representative : FIND CHINESE_NAME WORKfind_direct : FIND CHINESE_NAMEfind_style : FIND STYLE CHINESE_NAMEfind_calligrapher_style : FIND CHINESE_NAME STYLEfind_dynasty_calligraphers : FIND DYNASTY CALLIGRAPHERfind_calligrapher_info : FIND CHINESE_NAME INFO'
    
_lr_action_items = {'FIND':([0,],[9,]),'$end':([1,2,3,4,5,6,7,8,11,14,15,16,17,18,19,],[0,-1,-2,-3,-4,-5,-6,-7,-10,-8,-9,-14,-12,-11,-13,]),'CALLIGRAPHER':([9,13,],[10,19,]),'CHINESE_NAME':([9,10,12,],[11,14,18,]),'STYLE':([9,11,],[12,17,]),'DYNASTY':([9,],[13,]),'WORK':([11,],[15,]),'INFO':([11,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'find_calligrapher_detail':([0,],[2,]),'find_work_representative':([0,],[3,]),'find_style':([0,],[4,]),'find_dynasty_calligraphers':([0,],[5,]),'find_calligrapher_info':([0,],[6,]),'find_direct':([0,],[7,]),'find_calligrapher_style':([0,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> find_calligrapher_detail','query',1,'p_query','grammar.py',135),
  ('query -> find_work_representative','query',1,'p_query','grammar.py',136),
  ('query -> find_style','query',1,'p_query','grammar.py',137),
  ('query -> find_dynasty_calligraphers','query',1,'p_query','grammar.py',138),
  ('query -> find_calligrapher_info','query',1,'p_query','grammar.py',139),
  ('query -> find_direct','query',1,'p_query','grammar.py',140),
  ('query -> find_calligrapher_style','query',1,'p_query','grammar.py',141),
  ('find_calligrapher_detail -> FIND CALLIGRAPHER CHINESE_NAME','find_calligrapher_detail',3,'p_find_calligrapher_detail','grammar.py',147),
  ('find_work_representative -> FIND CHINESE_NAME WORK','find_work_representative',3,'p_find_work_representative','grammar.py',161),
  ('find_direct -> FIND CHINESE_NAME','find_direct',2,'p_find_direct','grammar.py',173),
  ('find_style -> FIND STYLE CHINESE_NAME','find_style',3,'p_find_style','grammar.py',201),
  ('find_calligrapher_style -> FIND CHINESE_NAME STYLE','find_calligrapher_style',3,'p_find_calligrapher_style','grammar.py',214),
  ('find_dynasty_calligraphers -> FIND DYNASTY CALLIGRAPHER','find_dynasty_calligraphers',3,'p_find_dynasty_calligraphers','grammar.py',227),
  ('find_calligrapher_info -> FIND CHINESE_NAME INFO','find_calligrapher_info',3,'p_find_calligrapher_info','grammar.py',243),
]
